//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  research: Research;
  researchConnection: ResearchConnection;
  philosophy: Philosophy;
  philosophyConnection: PhilosophyConnection;
  opinions: Opinions;
  opinionsConnection: OpinionsConnection;
  miscellaneous: Miscellaneous;
  miscellaneousConnection: MiscellaneousConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResearchArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResearchConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResearchFilter>;
};


export type QueryPhilosophyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPhilosophyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhilosophyFilter>;
};


export type QueryOpinionsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOpinionsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OpinionsFilter>;
};


export type QueryMiscellaneousArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMiscellaneousConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MiscellaneousFilter>;
};

export type DocumentFilter = {
  research?: InputMaybe<ResearchFilter>;
  philosophy?: InputMaybe<PhilosophyFilter>;
  opinions?: InputMaybe<OpinionsFilter>;
  miscellaneous?: InputMaybe<MiscellaneousFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Research | Philosophy | Opinions | Miscellaneous | Folder;

export type Research = Node & Document & {
  __typename?: 'Research';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  permalink?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  comments?: Maybe<Scalars['Boolean']['output']>;
  showToc?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ResearchFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  draft?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  permalink?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  categories?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  comments?: InputMaybe<BooleanFilter>;
  showToc?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ResearchConnectionEdges = {
  __typename?: 'ResearchConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Research>;
};

export type ResearchConnection = Connection & {
  __typename?: 'ResearchConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResearchConnectionEdges>>>;
};

export type Philosophy = Node & Document & {
  __typename?: 'Philosophy';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  permalink?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  comments?: Maybe<Scalars['Boolean']['output']>;
  showToc?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PhilosophyFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  draft?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  permalink?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  categories?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  comments?: InputMaybe<BooleanFilter>;
  showToc?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PhilosophyConnectionEdges = {
  __typename?: 'PhilosophyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Philosophy>;
};

export type PhilosophyConnection = Connection & {
  __typename?: 'PhilosophyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PhilosophyConnectionEdges>>>;
};

export type Opinions = Node & Document & {
  __typename?: 'Opinions';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  permalink?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  comments?: Maybe<Scalars['Boolean']['output']>;
  showToc?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OpinionsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  draft?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  permalink?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  categories?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  comments?: InputMaybe<BooleanFilter>;
  showToc?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type OpinionsConnectionEdges = {
  __typename?: 'OpinionsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Opinions>;
};

export type OpinionsConnection = Connection & {
  __typename?: 'OpinionsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OpinionsConnectionEdges>>>;
};

export type Miscellaneous = Node & Document & {
  __typename?: 'Miscellaneous';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  draft?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  excerpt?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  permalink?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  categories?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  keywords?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  comments?: Maybe<Scalars['Boolean']['output']>;
  showToc?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MiscellaneousFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  draft?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  permalink?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  categories?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  comments?: InputMaybe<BooleanFilter>;
  showToc?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type MiscellaneousConnectionEdges = {
  __typename?: 'MiscellaneousConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Miscellaneous>;
};

export type MiscellaneousConnection = Connection & {
  __typename?: 'MiscellaneousConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MiscellaneousConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateResearch: Research;
  createResearch: Research;
  updatePhilosophy: Philosophy;
  createPhilosophy: Philosophy;
  updateOpinions: Opinions;
  createOpinions: Opinions;
  updateMiscellaneous: Miscellaneous;
  createMiscellaneous: Miscellaneous;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateResearchArgs = {
  relativePath: Scalars['String']['input'];
  params: ResearchMutation;
};


export type MutationCreateResearchArgs = {
  relativePath: Scalars['String']['input'];
  params: ResearchMutation;
};


export type MutationUpdatePhilosophyArgs = {
  relativePath: Scalars['String']['input'];
  params: PhilosophyMutation;
};


export type MutationCreatePhilosophyArgs = {
  relativePath: Scalars['String']['input'];
  params: PhilosophyMutation;
};


export type MutationUpdateOpinionsArgs = {
  relativePath: Scalars['String']['input'];
  params: OpinionsMutation;
};


export type MutationCreateOpinionsArgs = {
  relativePath: Scalars['String']['input'];
  params: OpinionsMutation;
};


export type MutationUpdateMiscellaneousArgs = {
  relativePath: Scalars['String']['input'];
  params: MiscellaneousMutation;
};


export type MutationCreateMiscellaneousArgs = {
  relativePath: Scalars['String']['input'];
  params: MiscellaneousMutation;
};

export type DocumentUpdateMutation = {
  research?: InputMaybe<ResearchMutation>;
  philosophy?: InputMaybe<PhilosophyMutation>;
  opinions?: InputMaybe<OpinionsMutation>;
  miscellaneous?: InputMaybe<MiscellaneousMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  research?: InputMaybe<ResearchMutation>;
  philosophy?: InputMaybe<PhilosophyMutation>;
  opinions?: InputMaybe<OpinionsMutation>;
  miscellaneous?: InputMaybe<MiscellaneousMutation>;
};

export type ResearchMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  permalink?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  comments?: InputMaybe<Scalars['Boolean']['input']>;
  showToc?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PhilosophyMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  permalink?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  comments?: InputMaybe<Scalars['Boolean']['input']>;
  showToc?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type OpinionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  permalink?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  comments?: InputMaybe<Scalars['Boolean']['input']>;
  showToc?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type MiscellaneousMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  draft?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  permalink?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  categories?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  keywords?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  comments?: InputMaybe<Scalars['Boolean']['input']>;
  showToc?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ResearchPartsFragment = { __typename: 'Research', title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null };

export type PhilosophyPartsFragment = { __typename: 'Philosophy', title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null };

export type OpinionsPartsFragment = { __typename: 'Opinions', title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null };

export type MiscellaneousPartsFragment = { __typename: 'Miscellaneous', title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null };

export type ResearchQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResearchQuery = { __typename?: 'Query', research: { __typename: 'Research', id: string, title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ResearchConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResearchFilter>;
}>;


export type ResearchConnectionQuery = { __typename?: 'Query', researchConnection: { __typename?: 'ResearchConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResearchConnectionEdges', cursor: string, node?: { __typename: 'Research', id: string, title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PhilosophyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PhilosophyQuery = { __typename?: 'Query', philosophy: { __typename: 'Philosophy', id: string, title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PhilosophyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PhilosophyFilter>;
}>;


export type PhilosophyConnectionQuery = { __typename?: 'Query', philosophyConnection: { __typename?: 'PhilosophyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PhilosophyConnectionEdges', cursor: string, node?: { __typename: 'Philosophy', id: string, title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type OpinionsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OpinionsQuery = { __typename?: 'Query', opinions: { __typename: 'Opinions', id: string, title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type OpinionsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OpinionsFilter>;
}>;


export type OpinionsConnectionQuery = { __typename?: 'Query', opinionsConnection: { __typename?: 'OpinionsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OpinionsConnectionEdges', cursor: string, node?: { __typename: 'Opinions', id: string, title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MiscellaneousQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MiscellaneousQuery = { __typename?: 'Query', miscellaneous: { __typename: 'Miscellaneous', id: string, title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MiscellaneousConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MiscellaneousFilter>;
}>;


export type MiscellaneousConnectionQuery = { __typename?: 'Query', miscellaneousConnection: { __typename?: 'MiscellaneousConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MiscellaneousConnectionEdges', cursor: string, node?: { __typename: 'Miscellaneous', id: string, title: string, date?: string | null, draft?: boolean | null, description?: string | null, excerpt?: string | null, slug?: string | null, permalink?: string | null, tags?: Array<string | null> | null, categories?: Array<string | null> | null, keywords?: Array<string | null> | null, comments?: boolean | null, showToc?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ResearchPartsFragmentDoc = gql`
    fragment ResearchParts on Research {
  __typename
  title
  date
  draft
  description
  excerpt
  slug
  permalink
  tags
  categories
  keywords
  comments
  showToc
  body
}
    `;
export const PhilosophyPartsFragmentDoc = gql`
    fragment PhilosophyParts on Philosophy {
  __typename
  title
  date
  draft
  description
  excerpt
  slug
  permalink
  tags
  categories
  keywords
  comments
  showToc
  body
}
    `;
export const OpinionsPartsFragmentDoc = gql`
    fragment OpinionsParts on Opinions {
  __typename
  title
  date
  draft
  description
  excerpt
  slug
  permalink
  tags
  categories
  keywords
  comments
  showToc
  body
}
    `;
export const MiscellaneousPartsFragmentDoc = gql`
    fragment MiscellaneousParts on Miscellaneous {
  __typename
  title
  date
  draft
  description
  excerpt
  slug
  permalink
  tags
  categories
  keywords
  comments
  showToc
  body
}
    `;
export const ResearchDocument = gql`
    query research($relativePath: String!) {
  research(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResearchParts
  }
}
    ${ResearchPartsFragmentDoc}`;
export const ResearchConnectionDocument = gql`
    query researchConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResearchFilter) {
  researchConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResearchParts
      }
    }
  }
}
    ${ResearchPartsFragmentDoc}`;
export const PhilosophyDocument = gql`
    query philosophy($relativePath: String!) {
  philosophy(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PhilosophyParts
  }
}
    ${PhilosophyPartsFragmentDoc}`;
export const PhilosophyConnectionDocument = gql`
    query philosophyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PhilosophyFilter) {
  philosophyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PhilosophyParts
      }
    }
  }
}
    ${PhilosophyPartsFragmentDoc}`;
export const OpinionsDocument = gql`
    query opinions($relativePath: String!) {
  opinions(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OpinionsParts
  }
}
    ${OpinionsPartsFragmentDoc}`;
export const OpinionsConnectionDocument = gql`
    query opinionsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OpinionsFilter) {
  opinionsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OpinionsParts
      }
    }
  }
}
    ${OpinionsPartsFragmentDoc}`;
export const MiscellaneousDocument = gql`
    query miscellaneous($relativePath: String!) {
  miscellaneous(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MiscellaneousParts
  }
}
    ${MiscellaneousPartsFragmentDoc}`;
export const MiscellaneousConnectionDocument = gql`
    query miscellaneousConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MiscellaneousFilter) {
  miscellaneousConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MiscellaneousParts
      }
    }
  }
}
    ${MiscellaneousPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      research(variables: ResearchQueryVariables, options?: C): Promise<{data: ResearchQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchQueryVariables, query: string}> {
        return requester<{data: ResearchQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchQueryVariables, query: string}, ResearchQueryVariables>(ResearchDocument, variables, options);
      },
    researchConnection(variables?: ResearchConnectionQueryVariables, options?: C): Promise<{data: ResearchConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchConnectionQueryVariables, query: string}> {
        return requester<{data: ResearchConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResearchConnectionQueryVariables, query: string}, ResearchConnectionQueryVariables>(ResearchConnectionDocument, variables, options);
      },
    philosophy(variables: PhilosophyQueryVariables, options?: C): Promise<{data: PhilosophyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyQueryVariables, query: string}> {
        return requester<{data: PhilosophyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyQueryVariables, query: string}, PhilosophyQueryVariables>(PhilosophyDocument, variables, options);
      },
    philosophyConnection(variables?: PhilosophyConnectionQueryVariables, options?: C): Promise<{data: PhilosophyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyConnectionQueryVariables, query: string}> {
        return requester<{data: PhilosophyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PhilosophyConnectionQueryVariables, query: string}, PhilosophyConnectionQueryVariables>(PhilosophyConnectionDocument, variables, options);
      },
    opinions(variables: OpinionsQueryVariables, options?: C): Promise<{data: OpinionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OpinionsQueryVariables, query: string}> {
        return requester<{data: OpinionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OpinionsQueryVariables, query: string}, OpinionsQueryVariables>(OpinionsDocument, variables, options);
      },
    opinionsConnection(variables?: OpinionsConnectionQueryVariables, options?: C): Promise<{data: OpinionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OpinionsConnectionQueryVariables, query: string}> {
        return requester<{data: OpinionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OpinionsConnectionQueryVariables, query: string}, OpinionsConnectionQueryVariables>(OpinionsConnectionDocument, variables, options);
      },
    miscellaneous(variables: MiscellaneousQueryVariables, options?: C): Promise<{data: MiscellaneousQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MiscellaneousQueryVariables, query: string}> {
        return requester<{data: MiscellaneousQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MiscellaneousQueryVariables, query: string}, MiscellaneousQueryVariables>(MiscellaneousDocument, variables, options);
      },
    miscellaneousConnection(variables?: MiscellaneousConnectionQueryVariables, options?: C): Promise<{data: MiscellaneousConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MiscellaneousConnectionQueryVariables, query: string}> {
        return requester<{data: MiscellaneousConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MiscellaneousConnectionQueryVariables, query: string}, MiscellaneousConnectionQueryVariables>(MiscellaneousConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  