title: Deepak Shilkar
baseURL: 'https://deepakshilkar.in'
languageCode: en-us
theme: PaperMod
publishDir: public
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 10
googleAnalytics: G-L0T22MKVKM
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true
languages:
  en:
    title: Deepak Shilkar
    weight: 1
    contentDir: content/
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  env: production
  text_color: black
  author: Deepak Shilkar
  favicon: /images/general/logo.png
  site_logo: /images/general/logo.png
  description: Personal website and blog
  background_color_class: bg-navy
  recent_posts_number: 20
  disqusShortname: deepakshilkar1
  DateFormat: 'January 2, 2006'
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  images: /images/general/logo.png
  label:
    text: Deepak Shilkar
    icon: /images/general/logo.png
    iconHeight: 35
  profileMode:
    enabled: true
    title: Deepak Shilkar
    subtitle: >-
      As one treads the path of indifference, what rules shall bind and what
      prohibitions hinder?
    imageUrl: logo.png
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Academic
        url: /academic/
      - name: Tips
        url: /tips/
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog. Hope you find something interesting.
  socialIcons:
    - name: twitter
      url: 'https://twitter.com/deepakshilkar/'
    - name: github
      url: 'https://github.com/deepakshilkar/'
    - name: linkedin
      url: 'https://www.linkedin.com/in/deepakshilkar/'
  analytics:
    google:
      SiteVerificationTag: G-L0T22MKVKM
    bing:
      SiteVerificationTag: AEB5BB2B5D7825F92105F1B9A815B715
  cover:
    hidden: false
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: search
      name: Search
      url: /archive/
      weight: 100
    - identifier: about-me
      name: About
      url: /about/about.md
      weight: 20
outputs:
  home:
    - HTML
    - RSS
    - JSON
